# site properties and page defaults
title: yemiadesina
subtitle: 
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: contact@yemiadesina.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: yemiadesina
  twitter: yemiadesina
  youtube: yemiadesina
